# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: drestles <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/20 21:45:35 by drestles          #+#    #+#              #
#    Updated: 2018/11/20 21:51:38 by drestles         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all: 
	gcc -Wall -Wextra -Werror display_file.c -o ft_display_file

clean:
	rm -rf *.o

fclean: clean
	rm -rf $(NAME)
